# Generated by Django 6.0.6 on 2026-06-19 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('tenants', '0002_alter_tenant_type_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=10)),
                ('points', models.IntegerField()),
                ('motif', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_performance', to='authentication.personnel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_performance', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Transaction de performance',
                'verbose_name_plural': 'Transactions de performance',
            },
        ),
    ]
