# Generated by Django 6.0.6 on 2026-06-19 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_type_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('segment_cible', models.CharField(choices=[('toutes', 'Toutes les clientes'), ('inactives', 'Clientes inactives'), ('anniversaire', 'Anniversaires'), ('par_categorie_prestation', 'Par catégorie de prestation')], max_length=50)),
                ('valeur_segment', models.CharField(blank=True, max_length=100, null=True)),
                ('date_envoi', models.DateTimeField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('planifiee', 'Planifiée'), ('envoyee', 'Envoyée'), ('echouee', 'Échouée')], default='brouillon', max_length=20)),
                ('nombre_destinataires', models.IntegerField(blank=True, null=True)),
                ('nombre_coupons_utilises', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_campagnes', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Campagne SMS',
                'verbose_name_plural': 'Campagnes SMS',
            },
        ),
    ]
