# Generated by Django 6.0.6 on 2026-06-19 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        ('tenants', '0002_alter_tenant_type_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('motif', models.CharField(choices=[('vente_physique', 'Vente physique'), ('vente_en_ligne', 'Vente en ligne'), ('approvisionnement', 'Approvisionnement'), ('correction', 'Correction manuelle')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('quantite_avant', models.IntegerField()),
                ('quantite_apres', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='produits.produit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
            },
        ),
    ]
