# Generated by Django 6.0.6 on 2026-06-18 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('commandes', '0001_initial'),
        ('rendez_vous', '0001_initial'),
        ('tenants', '0002_alter_tenant_type_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_verse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_restant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('cash', 'Cash'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('en_ligne', 'En ligne')], max_length=20)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('partiel', 'Partiel'), ('impaye', 'Impayé')], default='impaye', max_length=10)),
                ('activite', models.CharField(max_length=100)),
                ('canal', models.CharField(choices=[('physique', 'Physique'), ('en_ligne', 'En ligne')], default='physique', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='clients.cliente')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='commandes.commande')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='rendez_vous.rendezvous')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'constraints': [models.CheckConstraint(condition=models.Q(('rendez_vous__isnull', True), ('commande__isnull', True), _connector='OR'), name='paiement_rdv_ou_commande_pas_les_deux')],
            },
        ),
    ]
