# Generated by Django 6.0.6 on 2026-06-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
