# Generated by Django 6.0.6 on 2026-06-18 03:16

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nom', models.CharField(max_length=150)),
                ('sous_domaine', models.CharField(max_length=100, unique=True)),
                ('domaine_custom', models.CharField(blank=True, max_length=255, null=True)),
                ('type_licence', models.CharField(choices=[('essai', "Période d'essai "), ('Mensuel', 'Abonnement mensuel'), ('trimestriel', 'Abonnement trimestriel'), ('semestriel', 'Abonnement semestriel'), ('annuel', 'Abonnement annuel')], default='essai', max_length=30)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('couleur_primaire', models.CharField(default='#E91E63', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#FFFFFF', max_length=7)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('suspendu', 'Suspendu'), ('essai', "Période d'essai")], default='essai', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
            },
        ),
    ]
