# Generated by Django 6.0.6 on 2026-06-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='type_licence',
            field=models.CharField(choices=[('essai', "Période d'essai "), ('Mensuel', 'Abonnement mensuel'), ('trimestriel', 'Abonnement trimestriel'), ('semestriel', 'Abonnement semestriel'), ('annuel', 'Abonnement annuel'), ('illimite', 'Abonnement illimité')], default='essai', max_length=30),
        ),
    ]
