# Generated by Django 6.0.6 on 2026-06-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_type_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='horaires',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='photo_couverture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='police',
            field=models.CharField(choices=[('poppins', 'Poppins'), ('nunito', 'Nunito'), ('lato', 'Lato'), ('montserrat', 'Montserrat')], default='poppins', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='theme',
            field=models.CharField(choices=[('elegant', 'Élégant'), ('moderne', 'Moderne'), ('minimaliste', 'Minimaliste')], default='elegant', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tiktok',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
