# Generated by Django 6.0.6 on 2026-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_adresse_tenant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='type_entreprise',
            field=models.CharField(blank=True, choices=[('beauty', 'Institut de beauté'), ('coiffure', 'Salon de coiffure'), ('restaurant', 'Restaurant'), ('quincaillerie', 'Quincaillerie'), ('hotel', 'Hôtel')], default='beauty', null=True),
        ),
    ]
