# Generated by Django 6.0.6 on 2026-07-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_type_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='statut_avant_suspension',
            field=models.CharField(blank=True, help_text='Mémorise le statut du tenant juste avant sa suspension, pour restauration fidèle.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='type_licence',
            field=models.CharField(choices=[('essai', "Période d'essai "), ('mensuel', 'Abonnement mensuel'), ('trimestriel', 'Abonnement trimestriel'), ('semestriel', 'Abonnement semestriel'), ('annuel', 'Abonnement annuel'), ('illimite', 'Abonnement illimité')], default='essai', max_length=30),
        ),
    ]
