# Generated by Django 6.0.6 on 2026-07-10 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_formule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalImpersonnalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire_email', models.EmailField(max_length=254)),
                ('date_acces', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('super_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonnalisations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_impersonnalisation', to='tenants.tenant')),
            ],
            options={
                'verbose_name': "Session d'impersonnalisation",
                'verbose_name_plural': "Sessions d'impersonnalisation",
                'ordering': ['-date_acces'],
            },
        ),
        migrations.CreateModel(
            name='JournalPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('impersonnalisation', 'Accès support (impersonnalisation)'), ('consultation_journal', "Consultation du journal d'un tenant"), ('creation_tenant', 'Création tenant'), ('suspension', 'Suspension tenant'), ('reactivation', 'Réactivation tenant'), ('activation_licence', 'Activation licence'), ('prolongation_essai', 'Prolongation essai'), ('ajout_jours_licence', 'Ajout de jours licence'), ('domaine_custom', 'Association domaine custom')], max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('super_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_plateforme', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_plateforme', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Journal plateforme',
                'verbose_name_plural': 'Journal plateforme',
                'ordering': ['-date'],
            },
        ),
    ]
