"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Ajouts Externes
import os # Pour interagir avec le système d'exploitation, notamment pour accéder aux variables d'environnement
from pathlib import Path # Pour gérer les chemins de fichiers de manière indépendante du système d'exploitation
from dotenv import load_dotenv # Charger les variables d'environnement depuis un fichier .env

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'FALSE') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    # Applications partagées par tous les tenants
    'django_tenants',  # Gestion multi-tenant
    'django.contrib.contenttypes',  # Gestion des types de contenu

    # Applications Django par défaut
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Applications tierces
    'rest_framework',  # Framework pour construire des APIs RESTful
    'rest_framework_simplejwt',  # Gestion des tokens JWT pour l'authentification

    # Applications locales au projet
]

MIDDLEWARE = [
    # Middleware de django-tenants pour gérer les requêtes multi-tenant
    'django_tenants.middleware.main.TenantMainMiddleware',
    # Middleware Django par défaut
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'
# URLs partagées (Super ADMIN, Résolution de domaine (tenant))
PUBLIC_SCHEMA_URLCONF = 'core.urls_public'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Configuration de django-tenants
TENANT_MODEL = "tenants.Tenant"  # Le modèle qui représente les tenants
TENANT_DOMAIN_MODEL = "tenants.Domain"  # Le modèle qui représente les domaines des tenants

# Apps Disponibles uniquement dans le contexte d'un tenant
TENANT_APPS = [
    'django.contrib.contenttypes',  # Gestion des types de contenu
    'django.contrib.auth',  # Gestion de l'authentification
    'django.contrib.admin',  # Interface d'administration
    'django.contrib.sessions',  # Gestion des sessions
    'django.contrib.messages',  # Gestion des messages
    'rest_framework',  # Framework pour construire des APIs RESTful
    'rest_framework_simplejwt',  # Gestion des tokens JWT pour l'authentification
    
    # Ajoutez ici d'autres applications spécifiques aux tenants
    'apps.clients',
    'apps.rendez_vous',
    'apps.caisse',
    'apps.ardoises',
    'apps.stock',
    'apps.produits',
    'apps.commandes',
    'apps.personnel',
    'apps.coupons',
    'apps.rapports',
    'apps.journal',
]

 # Apps partagées entre tous les tenants (niveau global)
SHARED_APPS = [
    'django_tenants',  # Gestion multi-tenant
    'django.contrib.contenttypes',  # Gestion des types de contenu
    'django.contrib.auth',  # Gestion de l'authentification
    'django.contrib.admin',  # Interface d'administration
    'django.contrib.sessions',  # Gestion des sessions
    'django.contrib.messages',  # Gestion des messages
    'django.contrib.staticfiles',  # Gestion des fichiers statiques
    'rest_framework',  # Framework pour construire des APIs RESTful
    'rest_framework_simplejwt',  # Gestion des tokens JWT pour l'authentification
    'drf_spectacular',  # Documentation automatique des APIs
    'rest_framework_simplejwt.token_blacklist',  # ← Blacklist des tokens

    'tenants',  # Application pour gérer les tenants et leurs domaines
    'public',  # Application pour gérer les fonctionnalités publiques
    'apps.authentication',
]

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

# Routing Multi-Tenant
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Custom User Model
AUTH_USER_MODEL = 'authentication.Utilisateur'

# Rest Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# Spectacular Settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'HosJos API',
    'DESCRIPTION': 'API de la plateforme SaaS de gestion pour salons de coiffure',
    'VERSION': '1.0.0',
}

# JWT configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Passer à 8heures pour correspondre au CDC
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}