# Generated by Django 6.0.6 on 2026-06-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_type_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_id', models.IntegerField(blank=True, null=True)),
                ('utilisateur_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type_action', models.CharField(max_length=100)),
                ('ressource', models.CharField(max_length=100)),
                ('ressource_id', models.IntegerField(blank=True, null=True)),
                ('details_avant', models.JSONField(blank=True, null=True)),
                ('details_apres', models.JSONField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_actions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Action journalisée',
                'verbose_name_plural': 'Journal des actions',
                'ordering': ['-date'],
            },
        ),
    ]
