# Generated by Django 6.0.6 on 2026-06-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0002_alter_tenant_type_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('montant_fixe', 'Montant fixe'), ('pourcentage', 'Pourcentage')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('usage_unique', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='clients.cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
