# Generated by Django 6.0.6 on 2026-06-19 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('commandes', '0001_initial'),
        ('coupons', '0001_initial'),
        ('rendez_vous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUtilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_utilisation', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_utilises', to='clients.cliente')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_utilisations', to='commandes.commande')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='coupons.coupon')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_utilisations', to='rendez_vous.rendezvous')),
            ],
            options={
                'verbose_name': 'Utilisation de coupon',
                'verbose_name_plural': 'Utilisations de coupons',
                'unique_together': {('coupon', 'cliente')},
            },
        ),
    ]
