# Generated by Django 6.0.6 on 2026-06-18 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('coupons', '0001_initial'),
        ('produits', '0001_initial'),
        ('tenants', '0002_alter_tenant_type_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('prete', 'Prête'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_preparation', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_livraison', models.CharField(choices=[('retrait', 'Retrait en salon'), ('livraison_domicile', 'Livraison à domicile')], default='retrait', max_length=20)),
                ('adresse_livraison', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='clients.cliente')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='coupons.coupon')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commande', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
