# Generated by Django 6.0.6 on 2026-06-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('clients', '0001_initial'),
        ('coupons', '0001_initial'),
        ('tenants', '0002_alter_tenant_type_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(max_length=100)),
                ('prix_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_minutes', models.IntegerField()),
                ('points_performance', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('prix_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note_cliente', models.TextField(blank=True, null=True)),
                ('apporte_meche', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='clients.cliente')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='coupons.coupon')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='authentication.personnel')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='rendez_vous.prestation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
            },
        ),
    ]
