# Generated by Django 6.0.6 on 2026-06-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='bloque_jusqu_a',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='tentatives_echouees',
            field=models.IntegerField(default=0),
        ),
    ]
